### ISSUE TITLE
Segmentation Fault when throwing a dye grenade

### ISSUE THREAD

**Issue by goran-benak** [Poligraf/OXCE-retrofw#1] opened 2021-03-11 19:57 UTC
I have made a post here https://openxcom.org/forum/index.php/topic,9529.0.html
describing an issue and uploading save, log and a configuration file.

Namely when throwing a dye grenade, after explosion I face a segmentation fault. 
[TFTD.RetroFW.SegmentationF.zip](https://github.com/Poligraf/OXCE-retrofw/files/6125656/TFTD.RetroFW.SegmentationF.zip)

**Comment by goran-benak** [comment] 2021-03-14 22:43
Update: I am also having a segmentation fault sometimes when I start a mission. It crashes before it goes in the menu for soldier equipment.

I tried to remove some items from the transporter before starting a mission and sometimes it starts the mission. Items removed are not consistent with not having a crash. When I remove all items except a dye grenade I can throw it without SF. 

I also tried "New Battle" from the menu to test If I can throw it there, and it works as it is intended, so the SF is not a consistent one.

**Comment by Poligraf** [comment] 2021-03-15 05:36
Hi Goran

Sorry for replying so late. I thought I have replied already, obviously that is not the case.

This bug is a known bug on oxce and it is not the ports fault.

I have had two other users who have reported a segmentation fault and I have verified the issue to be genuine.

I then tried to replicate the problem on a desktop computer and I could not.

After some investigation, I believe that the issue is to do with retrofw version.

Currently this affects all version of retrofw, but a future version 2.3 (not released as of time of writing this post) has fixed all segmentation faults for the other two users.

I am therefore inclined to not investigate this issue further as I blieve that retrofw 2.3 is going to be arriving in the near future.

Please note that the 2.3 version is currently in closed beta, but as far as I am concerned it is ready for an open beta release.

I will be recommending that all users who are playing sonic decompilation, xcom,,openbor and heroes of might and magic 2,Star Control 2 (Ur-Quan Masters) and race into space from my ports to upgrade.

I have noticed following issues (Sonic - segmentation fault, xcom segmentation fault, openbor sound issues where music becomes muted, heroes of might and magic 2 (current version stable but had to remove campaign option to improve stability), star control 2 sound issues and race into space game slower than it should be.

Hope that clarifies my stance on my ports somewhat.

**Comment by goran-benak** [comment] 2021-03-15 15:12
Hello Poligraf, thank you for your reply. I will just take a moment to thank you for all your hard work that brings so much joy to many, including me. I really appreciate it.  

Great news, that means that with new beta RetroFW 2.3 most of the memory problems will be removed. 
Then may I ask you just two more questions?

1) Can I post your answer on OpenXcom forum, linked above? (Or maybe If you have the time, you can do it?)
2) Will you continue your work on fheroes2 on campaign with the new RetroFW 2.3? 
 
I guess, that this issue can be closed. 
Best regards,
Goran.

**Comment by Poligraf** [comment] 2021-07-03 11:12
Issue should be fixed in retrofw 2.3 beta

Come on discord so you can check it out https://discord.com/invite/CX67MCH

**Closed as completed** 2021-07-03 11:12 UTC
